import {
  View,
  Text,
  Pressable,
  ScrollView,
  TextInput,
  Alert,
  Animated,
  Modal,
  StyleSheet,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { Image } from 'expo-image';
import * as Clipboard from 'expo-clipboard';
import * as WebBrowser from 'expo-web-browser';
import { useState, useRef, useEffect, useMemo } from 'react';
import { useGroceryStore } from '@/stores/groceryStore';
import { useDiscoverStore } from '@/stores/discoverStore';
import { fetchMacros, getPantryItems } from '@/lib/api';
import { getApiBaseUrl } from '@/lib/apiBaseUrl';
import { partitionForInstacart } from '@/lib/staples';
import { parseGroceryMeasurement, convertMeasurementToUs, formatGroceryQuantity } from '@/lib/instacartUtils';
import { fetchMealDetail } from '@/lib/mealdb';
import { supabase } from '@/lib/supabase';
import { MacroRow } from '@/components/ui/MacroRow';
import { AvatarButton } from '@/components/AvatarButton';
import { InstacartButton } from '@/components/grocery/InstacartButton';
import { useTheme } from '@/hooks/useTheme';
import type { GroceryItem, Recipe, Macros } from '@/types';

// ── Category helpers ────────────────────────────────────────────────────────

const CATEGORIES = ['Produce', 'Meat & Seafood', 'Dairy', 'Pantry', 'Frozen', 'Other'];

function formatSkipLine(staples: number): string {
  return `Skipping ${staples} staple${staples === 1 ? '' : 's'} you likely have`;
}

// Pantry hints use a normalized (trimmed + lowercased) key so they line up with
// pantryHints from partitionForInstacart. forcedStaples below uses the raw
// ingredient_name to match the staples-modal Add toggle — keep these conventions
// separate or the toggles silently no-op.
const normKey = (i: { ingredient_name: string }) => i.ingredient_name.trim().toLowerCase();

function categorize(name: string): string {
  const n = name.toLowerCase();
  if (/tomato|cucumber|onion|garlic|ginger|lemon|lime|lettuce|spinach|kale|pepper|capsicum|carrot|zucchini|mushroom|broccoli|cauliflower|celery|herb|basil|parsley|coriander|cilantro|thyme|rosemary|mint|avocado|sweet potato|potato|corn|pea|bean sprout|bok choy/.test(n)) return 'Produce';
  if (/chicken|beef|pork|lamb|turkey|duck|salmon|tuna|shrimp|prawn|fish|cod|tilapia|crab|lobster|bacon|pancetta|sausage|mince|steak|fillet/.test(n)) return 'Meat & Seafood';
  if (/milk|cheese|cream|butter|yogurt|feta|parmesan|mozzarella|cheddar|brie|gouda|egg|creme fraiche|mascarpone/.test(n)) return 'Dairy';
  if (/pasta|spaghetti|rice|flour|oil|olive oil|salt|pepper|spice|cumin|masala|paprika|turmeric|oregano|cinnamon|sauce|bread|tortilla|soy sauce|fish sauce|vinegar|sugar|honey|stock|broth|lentil|chickpea|coconut milk|tomato paste|canned|tinned/.test(n)) return 'Pantry';
  if (/frozen|ice cream/.test(n)) return 'Frozen';
  return 'Other';
}

function buildClipboardText(items: GroceryItem[], recipes: Recipe[], date: string): string {
  const grouped: Record<string, GroceryItem[]> = {};
  for (const item of items) {
    if (item.checked) continue;
    const cat = categorize(item.ingredient_name);
    if (!grouped[cat]) grouped[cat] = [];
    grouped[cat].push(item);
  }

  const lines: string[] = [
    `Mori Grocery List — ${date}`,
    recipes.length > 0 ? `Meals: ${recipes.map((r) => r.title).join(', ')}` : '',
    '',
  ].filter((l, i) => i !== 1 || l !== '');

  for (const cat of CATEGORIES) {
    if (!grouped[cat]?.length) continue;
    lines.push(cat.toUpperCase());
    for (const item of grouped[cat]) {
      const qty = item.quantity ? ` — ${item.quantity}${item.unit ? ' ' + item.unit : ''}` : '';
      lines.push(`• ${item.ingredient_name}${qty}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('Generated by Mori');
  return lines.join('\n');
}

// ── Undo banner ──────────────────────────────────────────────────────────────

const UNDO_DURATION = 5000; // ms

function UndoBanner({ count, message, onUndo, onDismiss }: {
  count: number;
  message?: string;
  onUndo: () => void;
  onDismiss: () => void;
}) {
  const colors = useTheme();
  const opacity = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.spring(opacity, { toValue: 1, useNativeDriver: true, speed: 20 }).start();
    const t = setTimeout(() => {
      Animated.timing(opacity, { toValue: 0, duration: 300, useNativeDriver: true }).start(onDismiss);
    }, UNDO_DURATION);
    return () => clearTimeout(t);
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <Animated.View style={{
      position: 'absolute', bottom: 160, left: 16, right: 16,
      backgroundColor: '#1A1A1A', borderRadius: 12,
      paddingVertical: 14, paddingHorizontal: 16,
      flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
      opacity,
      shadowColor: '#000', shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2, shadowRadius: 8, elevation: 8,
    }}>
      <Text style={{ color: 'white', fontSize: 14 }}>
        {message ?? `${count} item${count !== 1 ? 's' : ''} removed`}
      </Text>
      <Pressable onPress={onUndo}>
        <Text style={{ color: colors.primaryLight, fontSize: 14, fontWeight: '700' }}>Undo</Text>
      </Pressable>
    </Animated.View>
  );
}

// ── Meals modal ───────────────────────────────────────────────────────────────

function MealsModal({
  visible,
  recipes,
  onRemove,
  onClose,
}: {
  visible: boolean;
  recipes: Recipe[];
  onRemove: (recipe: Recipe) => void;
  onClose: () => void;
}) {
  const colors = useTheme();
  return (
    <Modal visible={visible} animationType="slide" transparent presentationStyle="overFullScreen">
      <View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' }}>
        {/* Backdrop tap closes modal */}
        <Pressable style={{ ...StyleSheet.absoluteFillObject }} onPress={onClose} />

        <View style={{
          backgroundColor: colors.card,
          borderTopLeftRadius: 20, borderTopRightRadius: 20,
          paddingBottom: 36,
          maxHeight: '70%',
        }}>
          {/* Handle */}
          <View style={{
            width: 36, height: 4, borderRadius: 2, backgroundColor: colors.border,
            alignSelf: 'center', marginTop: 12, marginBottom: 4,
          }} />

          <View style={{
            flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
            paddingHorizontal: 20, paddingVertical: 14,
          }}>
            <Text style={{ fontSize: 18, fontWeight: '700', color: colors.text }}>
              Meals on this list
            </Text>
            <Pressable onPress={onClose} hitSlop={12}>
              <Ionicons name="close" size={22} color={colors.textMuted} />
            </Pressable>
          </View>

          <ScrollView
            contentContainerStyle={{ paddingHorizontal: 16, gap: 10, paddingBottom: 8 }}
            showsVerticalScrollIndicator={false}
          >
            {recipes.map((recipe) => (
              <View key={recipe.id} style={{
                flexDirection: 'row', alignItems: 'center', gap: 14,
                backgroundColor: colors.background, borderRadius: 12,
                padding: 12,
              }}>
                <Image
                  source={recipe.image_url ? { uri: recipe.image_url } : undefined}
                  style={{ width: 60, height: 60, borderRadius: 10 }}
                  contentFit="cover"
                />
                <Text style={{
                  flex: 1, fontSize: 15, fontWeight: '600', color: colors.text,
                }} numberOfLines={2}>
                  {recipe.title}
                </Text>
                <Pressable
                  onPress={() => onRemove(recipe)}
                  hitSlop={10}
                  style={{
                    width: 32, height: 32, borderRadius: 16,
                    backgroundColor: '#FEE2E2',
                    alignItems: 'center', justifyContent: 'center',
                  }}
                >
                  <Ionicons name="trash-outline" size={16} color={colors.error} />
                </Pressable>
              </View>
            ))}
          </ScrollView>
        </View>
      </View>
    </Modal>
  );
}

// ── Main component ───────────────────────────────────────────────────────────

export default function GroceryList() {
  const colors = useTheme();
  const mode = useDiscoverStore((s) => s.mode);
  const unitSystem = useDiscoverStore((s) => s.unitSystem);
  const {
    list, selectedRecipes,
    toggleItem, deleteItem, clearChecked, restoreItems, removeRecipeFromList, clearAll, addCustomItem,
  } = useGroceryStore();

  const [editMode, setEditMode] = useState(false);
  const [undoItems, setUndoItems] = useState<GroceryItem[] | null>(null);
  const [undoKey, setUndoKey] = useState(0);
  const [checkUndoName, setCheckUndoName] = useState<string | null>(null);
  const [checkUndoKey, setCheckUndoKey] = useState(0);
  const [mealsVisible, setMealsVisible] = useState(false);
  const [addingItem, setAddingItem] = useState(false);
  const [newItemName, setNewItemName] = useState('');
  const [combinedMacros, setCombinedMacros] = useState<Macros | null>(null);
  const [instacartLoading, setInstacartLoading] = useState(false);
  const [instacartError, setInstacartError] = useState<string | null>(null);
  const [pantryNames, setPantryNames] = useState<Set<string>>(() => new Set());
  const [skippedModalVisible, setSkippedModalVisible] = useState(false);
  // forcedStaples: raw ingredient_name keys; resets per session (not persisted).
  const [forcedStaples, setForcedStaples] = useState<Set<string>>(() => new Set());
  // skippedPantry: normalized keys (see normKey); resets per session.
  const [skippedPantry, setSkippedPantry] = useState<Set<string>>(() => new Set());
  // Confirm dialog shown right before sending to Instacart when items are being left out.
  const [confirmSend, setConfirmSend] = useState<{ sendable: GroceryItem[]; skipped: GroceryItem[] } | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const { data: { session } } = await supabase.auth.getSession();
      const uid = session?.user?.id;
      if (!uid) return;
      try {
        const rows = await getPantryItems(uid);
        if (cancelled) return;
        setPantryNames(new Set(
          rows
            .map((r) => r.ingredient_name?.trim().toLowerCase())
            .filter((n): n is string => !!n)
        ));
      } catch {
        // Non-blocking: pantry filter just becomes a no-op if fetch fails.
      }
    })();
    return () => { cancelled = true; };
  }, []);

  // Fetch and aggregate macros for all selected recipes whenever the meal selection changes.
  // TheMealDB recipes have empty ingredients[] — fetch detail first to get real ingredient data.
  useEffect(() => {
    if (selectedRecipes.length === 0) { setCombinedMacros(null); return; }
    let cancelled = false;

    async function fetchAll() {
      const results = await Promise.all(
        selectedRecipes.map(async (r) => {
          // Get ingredient data — prefer existing, fall back to MealDetail fetch
          let ings = r.ingredients;
          if (ings.length === 0) {
            const detail = await fetchMealDetail(r.id).catch(() => null);
            ings = (detail?.ingredients ?? []).map((i) => ({ name: i.name, quantity: i.measure, unit: '' }));
          }
          return fetchMacros(r.title, ings, { externalId: r.id }).catch(() => null);
        })
      );
      if (cancelled) return;
      const valid = results.filter(Boolean) as Macros[];
      if (valid.length === 0) { setCombinedMacros(null); return; }
      setCombinedMacros({
        calories: valid.reduce((s, m) => s + m.calories, 0),
        protein: valid.reduce((s, m) => s + m.protein, 0),
        carbohydrates: valid.reduce((s, m) => s + m.carbohydrates, 0),
        fat: valid.reduce((s, m) => s + m.fat, 0),
        fibre: valid.reduce((s, m) => s + m.fibre, 0),
        isEstimated: valid.some((m) => m.isEstimated),
      });
    }

    fetchAll();
    return () => { cancelled = true; };
  }, [selectedRecipes.map((r) => r.id).join(',')]);

  function triggerUndo(items: GroceryItem[]) {
    setUndoItems(items);
    setUndoKey((k) => k + 1);
  }

  const items = list?.items ?? [];
  const checkedCount = items.filter((i) => i.checked).length;
  const uncheckedCount = items.length - checkedCount;

  const { pantryHints, skippedItems } = useMemo(
    () => partitionForInstacart(items.filter((i) => !i.checked), pantryNames),
    [items, pantryNames],
  );

  // Notice line counts only staples the user hasn't pulled back via the modal.
  const displayedSkippedStaples = skippedItems.filter(
    (i) => !forcedStaples.has(i.ingredient_name),
  ).length;

  // Build a quick lookup: recipeId → title
  const recipeMap = Object.fromEntries(selectedRecipes.map((r) => [r.id, r.title]));

  // Group unchecked items by category
  const grouped: Record<string, GroceryItem[]> = {};
  for (const item of items) {
    if (item.checked) continue;
    const cat = categorize(item.ingredient_name);
    if (!grouped[cat]) grouped[cat] = [];
    grouped[cat].push(item);
  }
  const checkedItems = items.filter((i) => i.checked);
  const categoriesWithItems = CATEGORIES.filter((c) => grouped[c]?.length > 0);

  function handleClearChecked() {
    const removed = clearChecked();
    if (removed.length > 0) triggerUndo(removed);
  }

  function handleUndo() {
    if (!undoItems) return;
    restoreItems(undoItems);
    setUndoItems(null);
  }

  async function handleCopy() {
    const date = new Date().toLocaleDateString('en-US', {
      month: 'long', day: 'numeric', year: 'numeric',
    });
    const text = buildClipboardText(items, selectedRecipes, date);
    await Clipboard.setStringAsync(text);
    Alert.alert('Copied!', 'Your grocery list has been copied to the clipboard.');
  }

  function cleanForSearch(name: string): string {
    // Only strip words that are pure prep (verbs the cook does) or non-product-defining
    // descriptors. Words like canned/frozen/dried/ground/crushed/whole identify a
    // DIFFERENT product on Instacart (canned crushed tomatoes ≠ fresh tomatoes;
    // ground beef ≠ steak; dried oregano ≠ fresh oregano) — never strip them.
    return name
      .replace(/\(.*?\)/g, '')
      // strip leading quantity + optional unit (e.g. "2 cups", "1/2 lb", "500g", "3")
      .replace(/^\d[\d\s/]*\s*(tsp|tbsp|teaspoon|tablespoon|cup|cups|oz|lb|lbs|g|kg|ml|l|clove|cloves|bunch|bunches|head|heads|piece|pieces|can|cans|stalk|stalks|sprig|sprigs|slice|slices)?\s*/i, '')
      // strip prep words after a comma ("onion, diced" → "onion")
      .replace(/,\s*(diced|minced|chopped|sliced|grated|julienned|peeled|deveined|trimmed|cubed|shredded|melted|softened|beaten|divided|optional|to taste|for garnish|for serving|as needed).*/i, '')
      // strip prep words not after a comma ("diced onion" → "onion")
      .replace(/\b(diced|minced|chopped|sliced|grated|julienned|peeled|deveined|trimmed|cubed|shredded|melted|softened|beaten|divided)\b/gi, '')
      // strip non-product descriptors (size, prep adverbs, preference flags)
      .replace(/\b(large|medium|small|extra-virgin|organic|finely|roughly|thinly)\b/gi, '')
      .replace(/\s{2,}/g, ' ')
      .trim();
  }

  function getUncheckedItemNames() {
    return items.filter((i) => !i.checked).map((i) => cleanForSearch(i.ingredient_name));
  }

  async function submitToInstacart(itemsToSend: GroceryItem[]) {
    setInstacartLoading(true);
    setInstacartError(null);

    try {
      const { data: { session } } = await supabase.auth.getSession();

      const instacartItems = itemsToSend.map((i) => {
        const name = cleanForSearch(i.ingredient_name);
        const rawMeasurement = parseGroceryMeasurement(i.quantity, i.unit);
        const measurement = rawMeasurement && unitSystem === 'us'
          ? convertMeasurementToUs(rawMeasurement)
          : rawMeasurement;
        const displayText = i.quantity
          ? `${i.ingredient_name} ${i.quantity}${i.unit ? ' ' + i.unit : ''}`.trim()
          : i.ingredient_name;
        return { name, displayText, ...(measurement ? { measurement } : {}) };
      });

      const title = selectedRecipes.length > 0
        ? `Mori: ${selectedRecipes.slice(0, 2).map((r) => r.title).join(', ')}${selectedRecipes.length > 2 ? ` +${selectedRecipes.length - 2} more` : ''}`
        : 'Mori Grocery List';

      const res = await fetch(`${getApiBaseUrl()}/api/instacart-cart`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(session?.access_token ? { Authorization: `Bearer ${session.access_token}` } : {}),
        },
        body: JSON.stringify({ items: instacartItems, title }),
      });

      if (!res.ok) throw new Error(`instacart-cart ${res.status}`);
      const data = await res.json();
      await WebBrowser.openBrowserAsync(data.url);
    } catch {
      setInstacartError('Could not create Instacart list. Please try again.');
    } finally {
      setInstacartLoading(false);
    }
  }

  async function handleInstacartOrder() {
    const uncheckedItems = items.filter((i) => !i.checked);
    if (uncheckedItems.length === 0) {
      Alert.alert('No items', 'All items are already checked off.');
      return;
    }

    const { sendable: baseSendable, skippedItems: allStaples } = partitionForInstacart(uncheckedItems, pantryNames);
    const finalSendable = [
      ...baseSendable.filter((i) => !skippedPantry.has(normKey(i))),
      ...allStaples.filter((i) => forcedStaples.has(i.ingredient_name)),
    ];

    if (finalSendable.length === 0) {
      const droppedNames = uncheckedItems.map((i) => i.ingredient_name);
      const previewNames = droppedNames.slice(0, 3).join(', ');
      const more = droppedNames.length > 3 ? ` …and ${droppedNames.length - 3} more` : '';
      const hasStaples = allStaples.length > 0;
      const buttons: { text: string; style?: 'cancel' | 'default'; onPress?: () => void }[] = [
        { text: 'Cancel', style: 'cancel' },
      ];
      if (hasStaples) {
        buttons.push({ text: 'Review', onPress: () => setSkippedModalVisible(true) });
      }
      buttons.push({ text: 'Send anyway', onPress: () => submitToInstacart(uncheckedItems) });
      Alert.alert(
        'Cart would be empty',
        `These items would be skipped: ${previewNames}${more}. Send them anyway?`,
        buttons,
      );
      return;
    }

    // Surface what's being left out so the user can catch surprises (e.g. fresh
    // garlic that only lives in STAPLES, or a pantry hint they actively skipped)
    // before the browser opens.
    const skippedFromCart = [
      ...allStaples.filter((i) => !forcedStaples.has(i.ingredient_name)),
      ...baseSendable.filter((i) => skippedPantry.has(normKey(i))),
    ];
    if (skippedFromCart.length > 0) {
      setConfirmSend({ sendable: finalSendable, skipped: skippedFromCart });
      return;
    }

    await submitToInstacart(finalSendable);
  }

  function handleClearAll() {
    Alert.alert('Clear list?', 'This will remove all recipes and ingredients.', [
      { text: 'Cancel', style: 'cancel' },
      { text: 'Clear', style: 'destructive', onPress: () => { clearAll(); setEditMode(false); } },
    ]);
  }

  // ── Empty state ────────────────────────────────────────────────────────────
  if (items.length === 0 && selectedRecipes.length === 0) {
    return (
      <SafeAreaView style={{ flex: 1, backgroundColor: colors.background }}>
        <View style={{ paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8 }}>
          <Text style={{ fontSize: 24, fontWeight: '700', color: colors.text }}>Grocery List</Text>
        </View>
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', gap: 16, paddingHorizontal: 32 }}>
          <Ionicons name="cart-outline" size={56} color={colors.border} />
          <Text style={{ fontSize: 18, fontWeight: '600', color: colors.text }}>Your list is empty</Text>
          <Text style={{ fontSize: 15, color: colors.textMuted, textAlign: 'center' }}>
            Add items manually or tap the cart icon on any recipe.
          </Text>
          {addingItem ? (
            <View style={{
              flexDirection: 'row', alignItems: 'center', gap: 8, width: '100%',
              backgroundColor: colors.card, borderRadius: 12,
              borderWidth: 1.5, borderColor: colors.primary,
              paddingVertical: 4, paddingHorizontal: 12,
            }}>
              <TextInput
                autoFocus
                value={newItemName}
                onChangeText={setNewItemName}
                placeholder="Item name..."
                placeholderTextColor={colors.textMuted}
                style={{ flex: 1, fontSize: 15, color: colors.text, paddingVertical: 9 }}
                returnKeyType="done"
                onSubmitEditing={() => {
                  if (newItemName.trim()) addCustomItem(newItemName.trim());
                  setNewItemName('');
                  setAddingItem(false);
                }}
                onBlur={() => {
                  if (newItemName.trim()) addCustomItem(newItemName.trim());
                  setNewItemName('');
                  setAddingItem(false);
                }}
              />
              <Pressable
                onPress={() => {
                  if (newItemName.trim()) addCustomItem(newItemName.trim());
                  setNewItemName('');
                  setAddingItem(false);
                }}
                style={{ backgroundColor: colors.primary, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8 }}
              >
                <Text style={{ color: 'white', fontWeight: '600', fontSize: 14 }}>Add</Text>
              </Pressable>
            </View>
          ) : (
            <Pressable
              onPress={() => setAddingItem(true)}
              style={{
                flexDirection: 'row', alignItems: 'center', gap: 8,
                backgroundColor: colors.primary, borderRadius: 12,
                paddingVertical: 14, paddingHorizontal: 24,
              }}
            >
              <Ionicons name="add" size={18} color="white" />
              <Text style={{ color: 'white', fontSize: 15, fontWeight: '600' }}>Add your first item</Text>
            </Pressable>
          )}
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: colors.background }}>
      {/* Header */}
      <View style={{
        flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
        paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8,
      }}>
        <Text style={{ fontSize: 24, fontWeight: '700', color: colors.text }}>Grocery List</Text>
        <View style={{ flexDirection: 'row', gap: 16, alignItems: 'center' }}>
          <Pressable onPress={() => setEditMode((e) => !e)}>
            <Text style={{ color: editMode ? colors.primary : colors.textMuted, fontSize: 14, fontWeight: '500' }}>
              {editMode ? 'Done' : 'Edit'}
            </Text>
          </Pressable>
          <Pressable onPress={handleClearAll}>
            <Text style={{ color: colors.error, fontSize: 14, fontWeight: '500' }}>Clear</Text>
          </Pressable>
          <AvatarButton />
        </View>
      </View>

      {/* Meals row — tappable, opens modal */}
      {selectedRecipes.length > 0 && (
        <Pressable
          onPress={() => setMealsVisible(true)}
          style={{
            flexDirection: 'row', alignItems: 'center',
            marginHorizontal: 16, marginBottom: 10,
            backgroundColor: colors.primaryLight,
            borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12,
            gap: 10,
          }}
        >
          {/* Stacked recipe thumbnails (up to 3) */}
          <View style={{ flexDirection: 'row' }}>
            {selectedRecipes.slice(0, 3).map((r, i) => (
              <Image
                key={r.id}
                source={{ uri: r.image_url ?? '' }}
                style={{
                  width: 32, height: 32, borderRadius: 8,
                  borderWidth: 2, borderColor: colors.primaryLight,
                  marginLeft: i === 0 ? 0 : -10,
                }}
                contentFit="cover"
              />
            ))}
          </View>
          <View style={{ flex: 1 }}>
            <Text style={{ fontSize: 14, fontWeight: '600', color: colors.primary }}>
              {selectedRecipes.length} {selectedRecipes.length === 1 ? 'meal' : 'meals'} selected
            </Text>
            <Text style={{ fontSize: 12, color: colors.primary, opacity: 0.7 }} numberOfLines={1}>
              {selectedRecipes[0]?.title}{selectedRecipes.length > 1 ? ` and ${selectedRecipes.length - 1} more` : ''}
            </Text>
          </View>
          <Ionicons name="chevron-forward" size={16} color={colors.primary} />
        </Pressable>
      )}

      <MealsModal
        visible={mealsVisible}
        recipes={selectedRecipes}
        onClose={() => setMealsVisible(false)}
        onRemove={(recipe) => {
          Alert.alert(
            'Remove meal?',
            `Remove "${recipe.title}" and its unique ingredients from the list?`,
            [
              { text: 'Cancel', style: 'cancel' },
              {
                text: 'Remove', style: 'destructive',
                onPress: () => {
                  removeRecipeFromList(recipe.id);
                  if (selectedRecipes.length === 1) setMealsVisible(false);
                },
              },
            ]
          );
        }}
      />

      {/* Meal Prep week summary header */}
      {mode === 'meal_prep' && selectedRecipes.length > 0 && (
        <View style={{
          marginHorizontal: 16, marginBottom: 8,
          backgroundColor: colors.weekBarBg,
          borderRadius: 10, paddingVertical: 10, paddingHorizontal: 14,
          flexDirection: 'row', alignItems: 'center', gap: 8,
        }}>
          <Ionicons name="calendar-outline" size={15} color={colors.primary} />
          <Text style={{ color: colors.primary, fontSize: 13, fontWeight: '600', flex: 1 }}>
            Week of {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
          </Text>
          <Text style={{ color: colors.primary, fontSize: 12 }}>
            {selectedRecipes.length} meal{selectedRecipes.length !== 1 ? 's' : ''} · {items.length} ingredient{items.length !== 1 ? 's' : ''}
          </Text>
        </View>
      )}

      {/* Tally header */}
      <View style={{
        flexDirection: 'row',
        backgroundColor: colors.primaryLight,
        marginHorizontal: 16,
        borderRadius: 12,
        padding: 14,
        marginBottom: 4,
      }}>
        <TallyItem icon="restaurant-outline" value={selectedRecipes.length}
          label={selectedRecipes.length === 1 ? 'meal' : 'meals'} />
        <TallyDivider />
        <TallyItem icon="list-outline" value={uncheckedCount} label="to buy" />
        {checkedCount > 0 && (
          <>
            <TallyDivider />
            <TallyItem icon="checkmark-circle-outline" value={checkedCount} label="done" />
          </>
        )}
      </View>
      {combinedMacros && (
        <View style={{ marginHorizontal: 16, marginTop: 8, marginBottom: 4 }}>
          <MacroRow macros={combinedMacros} compact />
        </View>
      )}

      {/* Item list */}
      <ScrollView style={{ flex: 1 }} contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 160 }}>
        {categoriesWithItems.map((category) => (
          <View key={category} style={{ marginBottom: 20 }}>
            <Text style={{
              fontSize: 12, fontWeight: '700', color: colors.textMuted,
              textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 8,
            }}>
              {category}
            </Text>
            {grouped[category].map((item) => {
              const key = normKey(item);
              const inPantry = pantryHints.has(key);
              const pantrySkipped = skippedPantry.has(key);
              return (
                <GroceryRow
                  key={item.ingredient_name}
                  item={item}
                  recipeMap={recipeMap}
                  editMode={editMode}
                  unitSystem={unitSystem}
                  inPantry={inPantry}
                  pantrySkipped={pantrySkipped}
                  onTogglePantrySkip={() => {
                    setSkippedPantry((prev) => {
                      const next = new Set(prev);
                      if (next.has(key)) next.delete(key);
                      else next.add(key);
                      return next;
                    });
                  }}
                  onToggle={() => {
                    toggleItem(item.ingredient_name);
                    setCheckUndoName(item.ingredient_name);
                    setCheckUndoKey((k) => k + 1);
                  }}
                  onDelete={() => {
                    const deleted = deleteItem(item.ingredient_name);
                    if (deleted) triggerUndo([deleted]);
                  }}
                />
              );
            })}
          </View>
        ))}

        {/* Add item — inline expandable input */}
        {!editMode && (
          <View style={{ marginBottom: 20 }}>
            {addingItem ? (
              <View style={{
                flexDirection: 'row', alignItems: 'center', gap: 8,
                backgroundColor: colors.card, borderRadius: 10,
                borderWidth: 1.5, borderColor: colors.primary,
                paddingVertical: 4, paddingHorizontal: 12,
              }}>
                <TextInput
                  autoFocus
                  value={newItemName}
                  onChangeText={setNewItemName}
                  placeholder="Item name..."
                  placeholderTextColor={colors.textMuted}
                  style={{ flex: 1, fontSize: 15, color: colors.text, paddingVertical: 9 }}
                  returnKeyType="done"
                  onSubmitEditing={() => {
                    if (newItemName.trim()) {
                      addCustomItem(newItemName.trim());
                      setNewItemName('');
                    }
                    setAddingItem(false);
                  }}
                  onBlur={() => {
                    if (newItemName.trim()) addCustomItem(newItemName.trim());
                    setNewItemName('');
                    setAddingItem(false);
                  }}
                />
                <Pressable
                  onPress={() => {
                    if (newItemName.trim()) addCustomItem(newItemName.trim());
                    setNewItemName('');
                    setAddingItem(false);
                  }}
                  style={{
                    backgroundColor: colors.primary, borderRadius: 8,
                    paddingHorizontal: 14, paddingVertical: 8,
                  }}
                >
                  <Text style={{ color: 'white', fontWeight: '600', fontSize: 14 }}>Add</Text>
                </Pressable>
              </View>
            ) : (
              <Pressable
                onPress={() => setAddingItem(true)}
                style={{
                  flexDirection: 'row', alignItems: 'center', gap: 8,
                  backgroundColor: colors.card, borderRadius: 10,
                  borderWidth: 1, borderColor: colors.border,
                  borderStyle: 'dashed',
                  paddingVertical: 12, paddingHorizontal: 14,
                }}
              >
                <Ionicons name="add-circle-outline" size={18} color={colors.primary} />
                <Text style={{ fontSize: 15, color: colors.primary, fontWeight: '500' }}>Add item</Text>
              </Pressable>
            )}
          </View>
        )}

        {/* Done section */}
        {checkedItems.length > 0 && (
          <View style={{ marginBottom: 20 }}>
            <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
              <Text style={{
                fontSize: 12, fontWeight: '700', color: colors.textMuted,
                textTransform: 'uppercase', letterSpacing: 0.8,
              }}>
                Done ({checkedItems.length})
              </Text>
              <Pressable onPress={handleClearChecked}>
                <Text style={{ color: colors.error, fontSize: 13, fontWeight: '500' }}>Remove</Text>
              </Pressable>
            </View>
            {checkedItems.map((item) => (
              <GroceryRow
                key={item.ingredient_name}
                item={item}
                recipeMap={recipeMap}
                editMode={editMode}
                unitSystem={unitSystem}
                inPantry={false}
                pantrySkipped={false}
                onTogglePantrySkip={() => {}}
                onToggle={() => toggleItem(item.ingredient_name)}
                onDelete={() => {
                  const deleted = deleteItem(item.ingredient_name);
                  if (deleted) triggerUndo([deleted]);
                }}
              />
            ))}
          </View>
        )}
      </ScrollView>

      {/* Skipped items detail modal */}
      <Modal
        visible={skippedModalVisible}
        animationType="slide"
        transparent
        presentationStyle="overFullScreen"
      >
        <View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' }}>
          <Pressable style={{ ...StyleSheet.absoluteFillObject }} onPress={() => setSkippedModalVisible(false)} />
          <View style={{
            backgroundColor: colors.card,
            borderTopLeftRadius: 20, borderTopRightRadius: 20,
            paddingBottom: 36, maxHeight: '60%',
          }}>
            <View style={{
              width: 36, height: 4, borderRadius: 2, backgroundColor: colors.border,
              alignSelf: 'center', marginTop: 12, marginBottom: 4,
            }} />
            <View style={{
              flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
              paddingHorizontal: 20, paddingVertical: 14,
            }}>
              <Text style={{ fontSize: 17, fontWeight: '700', color: colors.text }}>
                Staples we skipped
              </Text>
              <Pressable onPress={() => setSkippedModalVisible(false)} hitSlop={12}>
                <Ionicons name="close" size={22} color={colors.textMuted} />
              </Pressable>
            </View>
            <Text style={{ fontSize: 13, color: colors.textMuted, paddingHorizontal: 20, marginBottom: 12 }}>
              These won't be sent. Tap Add to include any you need.
            </Text>
            <ScrollView
              contentContainerStyle={{ paddingHorizontal: 20, gap: 6, paddingBottom: 8 }}
              showsVerticalScrollIndicator={false}
            >
              {skippedItems.map((item) => {
                const forced = forcedStaples.has(item.ingredient_name);
                return (
                  <View key={item.ingredient_name} style={{
                    flexDirection: 'row', alignItems: 'center', gap: 10,
                    backgroundColor: colors.background, borderRadius: 10,
                    paddingHorizontal: 14, paddingVertical: 10,
                  }}>
                    <Ionicons
                      name="flame-outline"
                      size={16}
                      color={colors.textMuted}
                    />
                    <Text style={{ flex: 1, fontSize: 14, color: colors.text }}>
                      {item.ingredient_name}
                    </Text>
                    <Pressable
                      onPress={() => {
                        const name = item.ingredient_name;
                        setForcedStaples((prev) => {
                          const next = new Set(prev);
                          if (next.has(name)) next.delete(name);
                          else next.add(name);
                          return next;
                        });
                      }}
                      style={{
                        borderWidth: 1,
                        borderColor: forced ? colors.primary : colors.border,
                        borderRadius: 8,
                        paddingHorizontal: 10,
                        paddingVertical: 4,
                        backgroundColor: forced ? colors.primary + '22' : 'transparent',
                      }}
                    >
                      <Text style={{ fontSize: 12, color: forced ? colors.primary : colors.textMuted, fontWeight: forced ? '600' : '400' }}>
                        {forced ? '✓ Added' : 'Add'}
                      </Text>
                    </Pressable>
                  </View>
                );
              })}
            </ScrollView>
          </View>
        </View>
      </Modal>

      {/* Pre-send confirm sheet — Mori-styled */}
      <Modal
        visible={confirmSend !== null}
        animationType="slide"
        transparent
        presentationStyle="overFullScreen"
        onRequestClose={() => setConfirmSend(null)}
      >
        <View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' }}>
          <Pressable style={{ ...StyleSheet.absoluteFillObject }} onPress={() => setConfirmSend(null)} />
          <View style={{
            backgroundColor: colors.card,
            borderTopLeftRadius: 24, borderTopRightRadius: 24,
            paddingBottom: 36, maxHeight: '70%',
          }}>
            <View style={{
              width: 36, height: 4, borderRadius: 2, backgroundColor: colors.border,
              alignSelf: 'center', marginTop: 12, marginBottom: 18,
            }} />

            <View style={{ paddingHorizontal: 24, marginBottom: 16 }}>
              <Text style={{
                fontFamily: 'Georgia',
                fontStyle: 'italic',
                fontWeight: '700',
                fontSize: 24,
                color: colors.text,
                marginBottom: 6,
              }}>
                Leaving these out
              </Text>
              <Text style={{
                fontSize: 13,
                color: colors.textMuted,
                lineHeight: 18,
              }}>
                {confirmSend ? `${confirmSend.skipped.length} item${confirmSend.skipped.length === 1 ? '' : 's'} won't be in your Instacart cart. Sending ${confirmSend.sendable.length}.` : ''}
              </Text>
            </View>

            <ScrollView
              contentContainerStyle={{ paddingHorizontal: 24, gap: 6, paddingBottom: 8 }}
              showsVerticalScrollIndicator={false}
              style={{ maxHeight: 280 }}
            >
              {confirmSend?.skipped.map((item) => {
                const isPantrySkip = skippedPantry.has(normKey(item));
                return (
                  <View key={item.ingredient_name} style={{
                    flexDirection: 'row', alignItems: 'center', gap: 10,
                    backgroundColor: colors.background, borderRadius: 12,
                    paddingHorizontal: 14, paddingVertical: 11,
                  }}>
                    <Ionicons
                      name={isPantrySkip ? 'home-outline' : 'flame-outline'}
                      size={15}
                      color={colors.textMuted}
                    />
                    <Text style={{ flex: 1, fontSize: 15, color: colors.text }}>
                      {item.ingredient_name}
                    </Text>
                    <Text style={{
                      fontSize: 10,
                      fontWeight: '600',
                      letterSpacing: 0.4,
                      color: colors.textMuted,
                      textTransform: 'uppercase',
                    }}>
                      {isPantrySkip ? 'pantry' : 'staple'}
                    </Text>
                  </View>
                );
              })}
            </ScrollView>

            <View style={{
              flexDirection: 'row',
              gap: 10,
              paddingHorizontal: 24,
              paddingTop: 18,
            }}>
              <Pressable
                onPress={() => setConfirmSend(null)}
                style={{
                  flex: 1,
                  borderWidth: 1,
                  borderColor: colors.border,
                  borderRadius: 14,
                  paddingVertical: 14,
                  alignItems: 'center',
                }}
              >
                <Text style={{ color: colors.text, fontSize: 15, fontWeight: '600' }}>
                  Cancel
                </Text>
              </Pressable>
              <Pressable
                onPress={() => {
                  const pending = confirmSend;
                  setConfirmSend(null);
                  if (pending) submitToInstacart(pending.sendable);
                }}
                style={{
                  flex: 1,
                  backgroundColor: colors.primary,
                  borderRadius: 14,
                  paddingVertical: 14,
                  alignItems: 'center',
                }}
              >
                <Text style={{ color: 'white', fontSize: 15, fontWeight: '600' }}>
                  Continue
                </Text>
              </Pressable>
            </View>
          </View>
        </View>
      </Modal>

      {/* Undo banner — delete/clear */}
      {undoItems && (
        <UndoBanner
          key={undoKey}
          count={undoItems.length}
          onUndo={handleUndo}
          onDismiss={() => setUndoItems(null)}
        />
      )}

      {/* Undo banner — accidental check */}
      {checkUndoName && (
        <UndoBanner
          key={`check-${checkUndoKey}`}
          count={1}
          message="Moved to Done"
          onUndo={() => { toggleItem(checkUndoName); setCheckUndoName(null); }}
          onDismiss={() => setCheckUndoName(null)}
        />
      )}

      {/* Bottom action bar */}
      <View style={{
        position: 'absolute', bottom: 0, left: 0, right: 0,
        backgroundColor: colors.card,
        borderTopWidth: 1, borderTopColor: colors.border,
        padding: 16, gap: 10,
      }}>
        <Pressable
          onPress={handleCopy}
          style={{
            backgroundColor: colors.primary, borderRadius: 12,
            paddingVertical: 15, alignItems: 'center',
            flexDirection: 'row', justifyContent: 'center', gap: 8,
          }}
        >
          <Ionicons name="copy-outline" size={18} color="white" />
          <Text style={{ color: 'white', fontSize: 16, fontWeight: '600' }}>Copy List</Text>
        </Pressable>

        {instacartError && (
          <Text style={{ color: colors.error, fontSize: 13, textAlign: 'center' }}>
            {instacartError}
          </Text>
        )}
        {displayedSkippedStaples > 0 && (
          <Pressable
            onPress={() => setSkippedModalVisible(true)}
            style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4 }}
          >
            <Text style={{ color: colors.textMuted, fontSize: 12 }}>
              {formatSkipLine(displayedSkippedStaples)}
            </Text>
            <Ionicons name="information-circle-outline" size={13} color={colors.textMuted} />
          </Pressable>
        )}
        <InstacartButton
          onPress={handleInstacartOrder}
          loading={instacartLoading}
          disabled={instacartLoading}
        />
      </View>
    </SafeAreaView>
  );
}

// ── Sub-components ───────────────────────────────────────────────────────────

function GroceryRow({
  item,
  recipeMap,
  editMode,
  unitSystem,
  inPantry,
  pantrySkipped,
  onTogglePantrySkip,
  onToggle,
  onDelete,
}: {
  item: GroceryItem;
  recipeMap: Record<string, string>;
  editMode: boolean;
  unitSystem: 'us' | 'metric';
  inPantry: boolean;
  pantrySkipped: boolean;
  onTogglePantrySkip: () => void;
  onToggle: () => void;
  onDelete: () => void;
}) {
  const colors = useTheme();
  // Build a readable source label for this ingredient
  const sourceLabel = (() => {
    if (item.recipe_ids.length === 0) return null;
    if (item.recipe_ids.length === 1) {
      const name = recipeMap[item.recipe_ids[0]];
      return name ?? null;
    }
    return `${item.recipe_ids.length} recipes`;
  })();

  return (
    <Pressable
      onPress={editMode ? undefined : onToggle}
      style={{
        flexDirection: 'row', alignItems: 'center',
        backgroundColor: colors.card, borderRadius: 10,
        paddingVertical: 11, paddingHorizontal: 13,
        marginBottom: 6,
        borderWidth: 1,
        borderColor: item.checked ? colors.primaryLight : colors.border,
        gap: 12,
      }}
    >
      {/* Delete button in edit mode, checkbox otherwise */}
      {editMode ? (
        <Pressable onPress={onDelete} hitSlop={8}>
          <View style={{
            width: 22, height: 22, borderRadius: 11,
            backgroundColor: colors.error,
            alignItems: 'center', justifyContent: 'center',
          }}>
            <Ionicons name="remove" size={14} color="white" />
          </View>
        </Pressable>
      ) : (
        <View style={{
          width: 22, height: 22, borderRadius: 11,
          borderWidth: 1.5,
          borderColor: item.checked ? colors.primary : colors.border,
          backgroundColor: item.checked ? colors.primary : 'transparent',
          alignItems: 'center', justifyContent: 'center',
        }}>
          {item.checked && <Ionicons name="checkmark" size={13} color="white" />}
        </View>
      )}

      {/* Name + source label */}
      <View style={{ flex: 1, opacity: pantrySkipped ? 0.55 : 1 }}>
        <Text style={{
          fontSize: 15,
          color: item.checked ? colors.textMuted : colors.text,
          textDecorationLine: item.checked ? 'line-through' : 'none',
        }}>
          {item.ingredient_name}
        </Text>
        {sourceLabel && !item.checked && (
          <Text style={{ fontSize: 11, color: colors.textMuted, marginTop: 1 }} numberOfLines={1}>
            {sourceLabel}
          </Text>
        )}
      </View>

      {/* Pantry hint pill */}
      {inPantry && !item.checked && !editMode && (
        <Pressable
          onPress={onTogglePantrySkip}
          hitSlop={8}
          style={{
            paddingHorizontal: 8,
            paddingVertical: 3,
            borderRadius: 10,
            borderWidth: 1,
            borderColor: pantrySkipped ? colors.primary : colors.border,
            backgroundColor: pantrySkipped ? colors.primaryLight : 'transparent',
          }}
        >
          <Text style={{
            fontSize: 10,
            fontWeight: '600',
            color: pantrySkipped ? colors.primary : colors.textMuted,
            letterSpacing: 0.3,
          }}>
            {pantrySkipped ? 'SKIPPED — TAP TO SEND' : 'IN PANTRY'}
          </Text>
        </Pressable>
      )}

      {/* Quantity */}
      {(item.quantity || item.unit) ? (
        <Text style={{ fontSize: 13, color: colors.textMuted }}>
          {formatGroceryQuantity(item.quantity, item.unit, unitSystem)}
        </Text>
      ) : null}
    </Pressable>
  );
}

function TallyItem({ icon, value, label }: { icon: string; value: number; label: string }) {
  const colors = useTheme();
  return (
    <View style={{ flex: 1, alignItems: 'center', gap: 2 }}>
      <Ionicons name={icon as any} size={18} color={colors.primary} />
      <Text style={{ fontSize: 18, fontWeight: '700', color: colors.primary }}>{value}</Text>
      <Text style={{ fontSize: 11, color: colors.primary, opacity: 0.75 }}>{label}</Text>
    </View>
  );
}

function TallyDivider() {
  const colors = useTheme();
  return (
    <View style={{ width: 1, backgroundColor: colors.primary, opacity: 0.2, marginHorizontal: 4, borderRadius: 1 }} />
  );
}
